### ISSUE TITLE
Check with czech checklist :)

### ISSUE THREAD

**Issue by benabraham** [Kossecki/ghc#16]
Details: https://www.vzhurudolu.cz/prirucka/checklist

# Obsah a HTML

- [x] Správný `<title>`
- [x] Správný `<meta description>`
- [x] Osnova nadpisů
- [x] Náhledy pro FB
- [x] Strukturovaná data pro Google
- [x] Obsah bez typografických chyb
- [x] Odkazy ven jsou platné
- [x] Správný `<meta viewport>`
- [x] Ikony a favikony
- [x] Validní HTML

# Přístupnost

- [x] Obsah a navigace dostupné bez Javascriptu
- [x] Kontrola podle WCAG
- [x] WAI-ARIA oblasti a HTML5 elementy
- [x] Ovládání tabulátorem
- [x] Správné typy inputů ve formulářích
- [x] Barevný kontrast

# Design

- [x] Grafika podporuje HD displeje typu Retina
- [x] Přátelský k mobilním uživatelům
- [x] Šablony pro chybové stránky 404

# Prohlížeče a kompatibilita

- [x] Plné zobrazení napříč prohlížeči a zařízeními
- [x] V pořádku bez CSS
- [x] Dostupnost hlavního obsahu ve starších prohlížečích
- [x] Tisková verze stránky
- [x] Funguje s blokovači reklamy

# Kvalita kódu

- [x] Kód dodržuje konvenci
- [x] Kvalita kódu v požadované úrovni
- [x] Javascriptový kód je pokrytý testy
- [x] Měření runtime chyb v JS kódu
- [x] Funkční testování
- [x] Kód je v produkční kvalitě
- [x] README.md

# Spouštění webu

- [x] sitemap.xml
- [x] Google Analytics
- [x] Registrace v nástrojích pro webmastery (Google Search Console)
- [x] Není zakázaná indexace vyhledávači
- [x] robots.txt
- [x] Vývojářské soubory nejsou na produkci
- [x] Přesměrování ze starých adres
- [x] Správné hlavičky serveru
- [x] Správně nastavené bezpečnostní hlavičky
- [x] HTTPS
